- name: "Automatic Repository Mirror"
  on: 
    push:
      branches:
        - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  jobs:
    mirror_job:
      runs-on: ubuntu-18.04
      steps:                                              # <-- must use actions/checkout@v1 before mirroring!
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:FiL-Studio/orbitviewr-client.git
          ssh_private_key:                                # <-- use 'secrets' to pass credential information.
            ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}