  name: "Automatic Repository Mirror"
  on: 
    push:
      branches:
        - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  jobs:
    mirror_job:
      runs-on: ubuntu-latest
      steps:
      - uses: ThamognyaKodi/mirror-git-repo@0.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
          EMAIL: ${{ github.event.pusher.email }}
          NAME: ${{ github.event.pusher.name }}
          BRANCH_FOR_DESTINATION_REPO: "main"
          BRANCH_ON_SOURCE_REPO: "main"
        with:
          source-repo: "git@github.com:FiL-Studio/Vera-Rubin.git"
          destination-repo: "git@github.com:FiL-Studio/orbitviewr-client.git"